export const TREATMENT_ACT_CODES = [
  'FISSURE_SEALING',
  'DIRECT_FILLING',
  'CROWN',
  'INLAY',
  'ONLAY',
  'VENEER',
  'BRIDGE',
  'ROOT_CANAL_MEDICATION',
  'ROOT_CANAL_FILLING',
  'ROOT_CANAL_REPAIR',
  'GLASS_FIBER_POST',
  'METAL_POST',
  'APICOECTOMY',
  'PARAPULPAL_PIN',
  'EXTRACTION',
  'IMPLANT_PLACEMENT',
  'HEALING_ABUTMENT',
  'LOCATOR_ATTACHMENT',
  'LOCATOR_OVERDENTURE',
  'BAR_ATTACHMENT',
  'BAR_OVERDENTURE',
  'PARTIAL_REMOVABLE_DENTURE',
  'COMPLETE_REMOVABLE_DENTURE',
  'CROWN_REPLACEMENT',
  'ORTHODONTIC_APPLIANCE',
] as const;

export const CLINICAL_FINDING_CODES = [
  'TOOTH_STATE',
  'TOOTH_SUBSTRATE',
  'CARIES',
  'ROOT_CARIES',
  'EXISTING_FILLING',
  'EXISTING_FIXED_RESTORATION',
  'EXISTING_ENDODONTIC_STATE',
  'EXISTING_PROSTHESIS',
  'CALCULUS',
  'CONTACT_POINT_DEFECT',
  'TOOTH_FRACTURE',
  'MOBILITY',
  'PERIODONTAL_INVOLVEMENT',
  'PERIAPICAL_LESION',
  'EXTRACTION_WOUND',
  'CROWN_LEAKAGE',
  'PULP_DIAGNOSIS',
  'APICAL_DIAGNOSIS',
  'ROOT_RESORPTION',
  'TOOTH_WEAR',
  'DISCOLORATION',
  'ORTHODONTIC_STATE',
  'PERI_IMPLANT_STATUS',
  'PERIODONTAL_MEASUREMENT',
  'FURCATION_INVOLVEMENT',
  'PLAQUE_FINDING',
  'GINGIVAL_FINDING',
] as const;

export type TreatmentActCode = (typeof TREATMENT_ACT_CODES)[number];
export type ClinicalFindingCode = (typeof CLINICAL_FINDING_CODES)[number];

export const isTreatmentActCode = (value: string): value is TreatmentActCode =>
  (TREATMENT_ACT_CODES as readonly string[]).includes(value);

export const isClinicalFindingCode = (
  value: string,
): value is ClinicalFindingCode =>
  (CLINICAL_FINDING_CODES as readonly string[]).includes(value);
