export const CLINIC_REPOSITORY = Symbol('CLINIC_REPOSITORY');
export const STAFF_MEMBER_REPOSITORY = Symbol('STAFF_MEMBER_REPOSITORY');
export const WORKING_HOURS_REPOSITORY = Symbol('WORKING_HOURS_REPOSITORY');
export const AUTH_SERVICE_PORT = Symbol('AUTH_SERVICE_PORT');
export const AUTH_GRPC_CLIENT = Symbol('AUTH_GRPC_CLIENT');
