export const APPOINTMENT_REPOSITORY = Symbol('APPOINTMENT_REPOSITORY');
export const QUEUE_REPOSITORY = Symbol('QUEUE_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const PATIENT_GRPC_CLIENT = Symbol('PATIENT_GRPC_CLIENT');
export const CLINIC_GRPC_CLIENT = Symbol('CLINIC_GRPC_CLIENT');
export const PATIENT_SERVICE_PORT = Symbol('PATIENT_SERVICE_PORT');
export const CLINIC_SERVICE_PORT = Symbol('CLINIC_SERVICE_PORT');
