export const PATIENT_REPOSITORY = Symbol('PATIENT_REPOSITORY');
export const INSURANCE_PROVIDER_REPOSITORY = Symbol(
  'INSURANCE_PROVIDER_REPOSITORY',
);
export const INSURANCE_TEMPLATE_REPOSITORY = Symbol(
  'INSURANCE_TEMPLATE_REPOSITORY',
);
export const PATIENT_INSURANCE_REPOSITORY = Symbol(
  'PATIENT_INSURANCE_REPOSITORY',
);
export const PATIENT_DOCUMENT_REPOSITORY = Symbol(
  'PATIENT_DOCUMENT_REPOSITORY',
);
